<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends EntityRepository
{
    public function byCategorie($categorie) {

        $qd =  $this->createQueryBuilder('u')
                    ->select('u')
                    ->where ('u.categorie = :categorie')
                    ->andWhere('u.disponible = 1')
                    ->orderBy('u.id')
                    ->setParameter('categorie',$categorie);
        return $qd->getQuery()->getResult() ;

    }

    public function recherche($chaine) {

        $qd =  $this->createQueryBuilder('u')
                    ->select('u')
                    ->where ('u.nom like :chaine')
                    ->andWhere('u.disponible = 1')
                    ->orderBy('u.id')
                    ->setParameter('chaine',$chaine);

        return $qd->getQuery()->getResult() ;

    }

    public function  findArray($array) {

        $qd =  $this->createQueryBuilder('u')
                    ->select('u')
                    ->where('u.id IN (:array)')
                    ->setParameter('array',$array) ;


        return $qd->getQuery()->getResult() ;
    }

}
