<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * tvaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tvaRepository extends EntityRepository
{
}
